server:
  port: 6071
  servlet:
    contextPath: /api

spring: 
  datasource:
    username: admin
    password: root
    url: "jdbc:mysql://localhost/productos"  

  jpa:
    hibernate:
      ddlAuto: update
    show-sql: false
jwt:
  secret: 7639848111F24212121B445421S545125D4212S5451A51115155151100000055051
  timeExpiration: 604800







